id: generic-ln882hki
name: Generic - LN882HKI
description: Generic - LN882HKI (LN882X board).
manufacturer: ''
esphome:
  platform: ln882x
  board: generic-ln882hki
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
