id: wb2l-m1
name: WB2L_M1 Wi-Fi Module
description: WB2L_M1 Wi-Fi Module (BK72XX board).
manufacturer: ''
esphome:
  platform: bk72xx
  board: wb2l-m1
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
