id: generic-rtl8710bn-2mb-788k
name: Generic - RTL8710BN (2M/788k)
description: Generic - RTL8710BN (2M/788k) (RTL87XX board).
manufacturer: ''
esphome:
  platform: rtl87xx
  board: generic-rtl8710bn-2mb-788k
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
