id: wr2
name: WR2 Wi-Fi Module
description: WR2 Wi-Fi Module (RTL87XX board).
manufacturer: ''
esphome:
  platform: rtl87xx
  board: wr2
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
