id: generic-rtl8720cf-2mb-896k
name: Generic - RTL8720CF (2M/896k)
description: Generic - RTL8720CF (2M/896k) (RTL87XX board).
manufacturer: ''
esphome:
  platform: rtl87xx
  board: generic-rtl8720cf-2mb-896k
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
