id: wr1
name: WR1 Wi-Fi Module
description: WR1 Wi-Fi Module (RTL87XX board).
manufacturer: ''
esphome:
  platform: rtl87xx
  board: wr1
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
