id: wr3le
name: WR3LE Wi-Fi Module
description: WR3LE Wi-Fi Module (RTL87XX board).
manufacturer: ''
esphome:
  platform: rtl87xx
  board: wr3le
  framework: arduino
hardware:
  connectivity:
  - wifi
tags: []
docs_url: https://esphome.io/components/libretiny.html
pins: []
