#!/usr/bin/env python3
"""One-time script to enrich board descriptions by fetching product pages.

Reads each board manifest that has a generic auto-generated description,
fetches the product_url, and extracts a better description from the page.

Usage:
    python script/enrich_boards.py [--dry-run] [--limit N]
"""

from __future__ import annotations

import argparse
import html as html_module
import re
import time
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

import yaml

DEFINITIONS_DIR = (
    Path(__file__).resolve().parent.parent / "esphome_device_builder" / "definitions" / "boards"
)

# Markers that indicate a description was auto-generated by sync_boards.py
AUTO_DESCRIPTION_MARKERS = ["-based board", "No description available"]


class MetaDescriptionParser(HTMLParser):
    """Extract meta description and og:description from HTML."""

    def __init__(self) -> None:
        super().__init__()
        self.meta_description: str = ""
        self.og_description: str = ""
        self.title: str = ""
        self._in_title = False
        self._title_parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "title":
            self._in_title = True
            self._title_parts = []
        if tag != "meta":
            return
        attr_dict = dict(attrs)
        name = (attr_dict.get("name") or "").lower()
        prop = (attr_dict.get("property") or "").lower()
        content = attr_dict.get("content", "")
        if name == "description" and content:
            self.meta_description = content
        if prop == "og:description" and content:
            self.og_description = content

    def handle_data(self, data: str) -> None:
        if self._in_title:
            self._title_parts.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag == "title" and self._in_title:
            self._in_title = False
            self.title = "".join(self._title_parts).strip()


def _clean_html_text(text: str) -> str:
    """Clean HTML entities, extra whitespace, etc."""
    # Decode HTML entities (&amp; &nbsp; &#39; etc.)
    text = html_module.unescape(text)
    # Remove any remaining HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _truncate_to_sentence(text: str, max_len: int = 300) -> str:
    """Truncate text to the last complete sentence within max_len."""
    if len(text) <= max_len:
        return text
    # Find the last sentence boundary within max_len
    truncated = text[:max_len]
    last_period = truncated.rfind(". ")
    if last_period > 50:
        return truncated[: last_period + 1]
    # No good sentence boundary — truncate at word boundary
    last_space = truncated.rfind(" ")
    if last_space > 50:
        return truncated[:last_space] + "..."
    return truncated + "..."


def _fetch_page_description(url: str) -> str | None:
    """Fetch a URL and extract a description from meta tags."""
    try:
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; ESPHome Device Builder)",
                "Accept": "text/html",
            },
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            # Only read first 50KB — meta tags are in the head
            raw_html = resp.read(50_000).decode("utf-8", errors="ignore")
    except Exception:
        return None

    parser = MetaDescriptionParser()
    try:
        parser.feed(raw_html)
    except Exception:
        return None

    # Prefer og:description > meta description
    desc = parser.og_description or parser.meta_description
    if not desc:
        return None

    desc = _clean_html_text(desc)
    desc = _truncate_to_sentence(desc)

    # Skip if too short or looks like boilerplate
    if len(desc) < 20:
        return None
    boilerplate = ["cookie", "javascript", "enable javascript", "sign in", "log in"]
    if any(bp in desc.lower() for bp in boilerplate):
        return None

    # Ensure it ends with a period
    if not desc.endswith((".", "...")):
        desc += "."

    return desc


def _needs_enrichment(data: dict) -> bool:
    """Check if a board manifest needs a better description."""
    desc = data.get("description", "")
    return any(marker in desc for marker in AUTO_DESCRIPTION_MARKERS)


def enrich(dry_run: bool = False, limit: int = 0) -> None:
    """Run the enrichment."""
    enriched = 0
    failed = 0
    skipped = 0

    manifests = sorted(DEFINITIONS_DIR.glob("*/manifest.yaml"))

    for manifest in manifests:
        if limit and enriched >= limit:
            break

        data = yaml.safe_load(manifest.read_text())

        if not _needs_enrichment(data):
            skipped += 1
            continue

        url = data.get("product_url", "")
        if not url:
            failed += 1
            continue

        board_id = manifest.parent.name
        desc = _fetch_page_description(url)

        if not desc:
            print(f"  MISS  {board_id:40s} (no usable description at {url})")
            failed += 1
            # Be polite with rate limiting
            time.sleep(0.3)
            continue

        if dry_run:
            print(f"  [dry]  {board_id:40s} -> {desc[:80]}...")
        else:
            # Update the manifest
            text = manifest.read_text()
            old_desc = data["description"]
            # Escape quotes in description for YAML
            safe_desc = desc.replace('"', '\\"')
            text = text.replace(
                f'description: "{old_desc}"',
                f'description: "{safe_desc}"',
            )
            manifest.write_text(text)
            print(f"  OK    {board_id:40s} -> {desc[:80]}...")

        enriched += 1
        # Be polite — don't hammer servers
        time.sleep(0.5)

    print(f"\nDone: {enriched} enriched, {failed} no description found, {skipped} already good")


def main() -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, default=0, help="Max boards to enrich (0=all)")
    args = parser.parse_args()
    enrich(dry_run=args.dry_run, limit=args.limit)


if __name__ == "__main__":
    main()
